module.exports = {
  Gold: [
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Bullseye", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Guiding Star", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Healing Light", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Lightning Strike", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Slow Dart", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Sky Piercer", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Wind Talker", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Charged Shield", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Cleansing Chalice", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Ethereal Guardian", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"5", pak:"Y", brag:"N", card:"Hammer of God", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"N", brag:"N", card:"Holy Shower", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Sword of Light", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"5", pak:"Y", brag:"N", card:"Wrath of God", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Acid Splash", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Annoying Elves", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Root Arrow", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"N", brag:"N", card:"Song of Nature", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Box of Frogs", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Candy Cauldron", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"N", brag:"N", card:"Charm of Making", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Storm's End", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Poisonous Currents", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Vine Wrap", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Witch's Brew", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Fellcrest Lullaby", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"5", pak:"Y", brag:"N", card:"Rocking Roll", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Peace Pipe", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Sweet Corn", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"The Spice", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Veggie Skewer", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Fairy Shield", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Healing Splash", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Ivywood Piercer", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Fuming Bunny", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Healing Oils", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Hot Chestnuts", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Iron Break", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Firestorm", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Lava Wave", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Volcano", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Blazefury", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Bearded Hatchet", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Caber Toss", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"6", pak:"Y", brag:"N", card:"Dragonslayer", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Firewall", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Flame On", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Bloodthirster", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Espresso Shot", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Piercing Hellfire", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Speed of Light", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Rain of Fire", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Quad Slash", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Night Cap", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Nightmare", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Moonbeam", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Snake Charmer", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Spent Force", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Pumpkin Field", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Backstab", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Flared Up", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Hard Luck", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Heart Breaker", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Shadow Steps", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Spiked Trap", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Out of Sight", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"5", pak:"Y", brag:"N", card:"Avalanche", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Channeling Chi", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Easter Eggs", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Meditation", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Monk Fu", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Smelling Salts", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Quivering Sole", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"5", pak:"Y", brag:"N", card:"Deep Breath", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Ice Shard", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Kelpies Call", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Ride of the Valkyries", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"Silverlake Sword", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Wet Kiss", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Wyrmslayer", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Hoist the Colours", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Megalodon Tooth", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"3", pak:"Y", brag:"N", card:"Shark Cannon", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Sharp Tongue", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"4", pak:"Y", brag:"N", card:"The Kraken", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Voodoo Ritual", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Divine Storm", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Flash of Lightning", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Justicar", elmnt:"air"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"The Equalizer", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Hurricane Barrier", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Quicksilver", elmnt:"air"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Wind Dart", elmnt:"air"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Crippling Spell", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Deadly Venom", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Green Ray", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Toxic Vengeance", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Clay Shower", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Merry Christmas", elmnt:"earth"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Uber Cornholio", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Elven Precision", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Puck's Grace", elmnt:"earth"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Shield of The Nature", elmnt:"earth"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Blazing Ray", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Pyroclastic Sphere", elmnt:"fire"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Scorching Flames", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Dragon Skin", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Igni Ferroque", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Salamander Ale", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Pyroclastic Strike", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Pierced Heart", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Pyro Dagger", elmnt:"fire"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Turkey Sagitta", elmnt:"fire"},
        {cls:"might", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Magnet Shield", elmnt:"neutral"},
        {cls:"skill", rar:"4:star:", rarl:":star2:", trn:"2", pak:"Y", brag:"N", card:"Safeguard", elmnt:"neutral"},
        {cls:"magic", rar:"4:star:", rarl:":star2:", trn:"1", pak:"Y", brag:"N", card:"Rejuvenate All", elmnt:"neutral"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"N", card:"Adorable Pugs", elmnt:"neutral"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Apollo's Arrow", elmnt:"neutral"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Necropower", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Malefix", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Retribution Curse", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Vampiric Lord", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Obscuring Explode", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Ninja Grenade", elmnt:"spirit"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Whispering Blade", elmnt:"spirit"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Ascetic Lesson", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Frost Ray", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Poseidon's Will", elmnt:"water"},
        {cls:"magic", rar:"4:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Triton's Will", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Fafnir's Blood", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Ice Queen Protector", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Mead Gulp", elmnt:"water"},
        {cls:"might", rar:"4:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Silverlake Shards", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Ancient Mariner", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Caribbean Cocktail", elmnt:"water"},
        {cls:"skill", rar:"4:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Mark of Vengeance", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Barrier Crusher", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Dagger of Truth", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Defensive Strike", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Divine Thunder", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Lightning Spear", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Quartzstone", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"5", pak:"Y", brag:"N", card:"Shocking Axe", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Shocking Bag", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Shocking Sword", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"N", card:"Storm Dagger", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Sword of Justice", elmnt:"air"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Vigilant Shield", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Diverting Pin", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Eletric Shot", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Perfect Dart", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Pin Barrage", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Shocking Dart", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Shocking Pin", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Storm Dart", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Storm Edge", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Tempest Amulet", elmnt:"air"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Wind Barrier", elmnt:"air"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Crippling Bolt", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Earth Quake", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Feed the Toxins", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Mischievous Break", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Poison Cloud", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Poison Grenade", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Stunning Earth", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Terra Missile", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Toxic Bolt", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Witchcraft", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Byson Shield", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Christmas Tree", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Cornholio", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Dirty Bomb", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Piercing Spear", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Poisonous Dung", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Sundered Rocks", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Terra Sword", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"The Scabber", elmnt:"earth"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Warped Seeds", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Bleeding Thorn", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Diverting Tip", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Ivywood Amulet", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Fairy Blessing", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Forest Barrier", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Perfect Sight", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Poisonous Dart", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Poisonous Tip", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Sleeping Dust", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Terra Tip", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Tip Barrage", elmnt:"earth"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"N", card:"Rooster Arrow", elmnt:"earth"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Blinding Flame", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Burning Blast", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Burning Grenade", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Burning Missile", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Cloak of Flames", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Fire Bolt", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Oil Spill", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Stunning Heat", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Burning Blade", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Burning Club", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Burning Dagger", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"5", pak:"Y", brag:"N", card:"Fiery Axe", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Fuel the Fire", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Furious Fist", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Hot Boulder", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Magmatic Rocks", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Monster Juice", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Mutton Chops", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Oil Bag", elmnt:"fire"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Salamander Skin", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Bleeding Heart", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Boiling Coffee", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Burning Disc", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Diverting Disc", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Fiery Stars", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Perfect Cut", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Oil Dart", elmnt:"fire"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Turkey Arrow", elmnt:"fire"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Blinding Spirit", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Cloak Party", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Confuse Cloud", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Confuse Grenade", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Darken Missile", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Discharging Ray", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Hex", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Life Leecher", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Menacing Gloom", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Setback", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Vampiric Bats", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Cloaked", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Confuse Dart", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Darkness Spike", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Defrost Amulet", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Explosive Gadget", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Leech Boomerang", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Perfect Stab", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Smoke Bomb", elmnt:"spirit"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Spike Barrage", elmnt:"spirit"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"N", brag:"Y", card:"Apnoea", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Breaking Chakra", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Ice Bolt", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Chill Grenade", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Chill Missile", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Chill Stones", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Chilling Jab", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Karmick Kick", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Karmic Protection", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Snowballs Squall", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Tidal Kick", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Tides Control", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Wet Missile", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"5", pak:"Y", brag:"N", card:"Chill Axe", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Chill Blade", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Chill Club", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"N", brag:"Y", card:"Chilling Shards", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Frostbite Shield", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Glacier", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Mammoth Shield", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Mead Sip", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Piercing Shard", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Valkyries\'s Shield' , element:'water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Wet Bag", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Wet Dagger", elmnt:"water"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Wyrm\'s Blood", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Black Spot", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Grog Bottle", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Mistral Strike", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Oyster Blunderbuss", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"N", brag:"Y", card:"Perfect Slash", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Piranha Pistol", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Rum Shower", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Stingray Dart", elmnt:"water"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"N", brag:"Y", card:"Tropical Juice", elmnt:"water"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Arcane Grenade", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Arcane Missile", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Drop Shield", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Epicentre", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Healing Soul", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Guide Dog", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Party Bubble", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Sleeping Sceptre", elmnt:"neutral"},
        {cls:"magic", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Stunning Staff", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Bleeding Dagger", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Explosive Bag", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Gravy Barrel", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Impale Shield", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Interrupt Sword", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Power Shield", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Stunning Boulder", elmnt:"neutral"},
        {cls:"might", rar:"3:star:", rarl:"", trn:"5", pak:"Y", brag:"N", card:"War Axe", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Bleeding Edge", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Combustibolt", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"4", pak:"Y", brag:"N", card:"Destructive Arrow", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Diverting Arrow", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Diverting Dart", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"2", pak:"Y", brag:"N", card:"Hasty Arrow", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"3", pak:"Y", brag:"N", card:"Interrupt Arrow", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Lentil Soup", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Shielding Light", elmnt:"neutral"},
        {cls:"skill", rar:"3:star:", rarl:"", trn:"1", pak:"Y", brag:"N", card:"Silver Dart", elmnt:"neutral"},
  ],
  Diamond: [
    {rar:"5:star:", pak:"Y", efct:"accuracyup",efct1:"",efct2:"",efct3:"",perk:"shock", card:"Bullseye", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"accuracyup",efct1:"",efct2:"",efct3:"",perk:"shock", card:"Bullseye", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"perfectshot",efct1:"shock",efct2:"accuracyup",efct3:"",perk:"haste", card:"Guiding Star", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"shock",efct1:"accuracyup",efct2:"",efct3:"",perk:"critical", card:"Guiding Star", elmnt:"air"},
    {rar:"5:star:", pak:"N", efct:"immunity",efct1:"",efct2:"",efct3:"",perk:"accuracyup", card:"Healing Light", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"accuracyup", card:"Healing Light", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"splash",efct1:"shock",efct2:"",efct3:"",perk:"critical", card:"Lightning Strike", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"splash",efct1:"shock",efct2:"",efct3:"",perk:"critical", card:"Lightning Strike", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"perfectshot",efct1:"slow",efct2:"interrupt",efct3:"",perk:"critical", card:"Slow Dart", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"perfectshot",efct1:"slow",efct2:"",efct3:"",perk:"interrupt", card:"Slow Dart", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"pierce",efct1:"interrupt",efct2:"",efct3:"",perk:"critical", card:"Sky Piercer", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Sky Piercer", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"awaken",efct1:"",efct2:"",efct3:"",perk:"evade", card:"Wind Talker", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"awaken",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Wind Talker", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"taunt",efct1:"counter",efct2:"",efct3:"",perk:"accuracyup", card:"Charged Shield", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"taunt",efct1:"counter",efct2:"",efct3:"",perk:"accuracyup", card:"Charged Shield", elmnt:"air"},
    {rar:"5:star:", pak:"N", efct:"immunity",efct1:"cure",efct2:"",efct3:"",perk:"chargetrait", card:"Cleansing Chalice", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"immunity",efct1:"cure",efct2:"",efct3:"",perk:"critical", card:"Cleansing Chalice", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"hpup",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Ethereal Guardian", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"hpup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Ethereal Guardian", elmnt:"air"},
    {rar:"5:star:", pak:"N", efct:"splash",efct1:"shock",efct2:"",efct3:"",perk:"weakair", card:"Hammer of God", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"splash",efct1:"shock",efct2:"",efct3:"",perk:"weakair", card:"Hammer of God", elmnt:"air"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"drown",efct2:"burn",efct3:"awaken",perk:"shieldbind", card:"Holy Shower", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"drown",efct2:"burn",efct3:"awaken",perk:"critical", card:"Holy Shower", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"perfectshot",efct1:"accuracydown",efct2:"weakair",efct3:"",perk:"shieldbind", card:"Sword of Light", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"perfectshot",efct1:"accuracydown",efct2:"",efct3:"",perk:"weakair", card:"Sword of Light", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"weakair",efct2:"",efct3:"",perk:"shock", card:"Wrath of God", elmnt:"air"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"weakair",efct2:"",efct3:"",perk:"shock", card:"Wrath of God", elmnt:"air"},
    {rar:"5:star:", pak:"Y", efct:"splash",efct1:"poison",efct2:"",efct3:"",perk:"weakearth", card:"Acid Splash", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"splash",efct1:"poison",efct2:"",efct3:"",perk:"weakearth", card:"Acid Splash", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"flurry",efct1:"accuracydown",efct2:"",efct3:"",perk:"interrupt", card:"Annoying Elves", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"flurry",efct1:"accuracydown",efct2:"",efct3:"",perk:"interrupt", card:"Annoying Elves", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"perfectshot",efct1:"preventhaste",efct2:"defencedown",efct3:"",perk:"critical", card:"Root Arrow", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"perfectshot",efct1:"preventhaste",efct2:"",efct3:"",perk:"defencedown", card:"Root Arrow", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"splash",efct1:"sleep",efct2:"poison",efct3:"pierce",perk:"speedup", card:"Song of Nature", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"splash",efct1:"sleep",efct2:"poison",efct3:"",perk:"critical", card:"Song of Nature", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"poison",efct3:"",perk:"critical", card:"Box of Frogs", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"poison",efct3:"",perk:"critical", card:"Box of Frogs", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"haste",efct2:"awaken",efct3:"",perk:"cure", card:"Candy Cauldron", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"haste",efct2:"regen",efct3:"",perk:"cure", card:"Candy Cauldron", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"preventhaste",efct1:"hpdown",efct2:"",efct3:"",perk:"slow", card:"Charm of Making", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"preventhaste",efct1:"",efct2:"",efct3:"",perk:"hpdown", card:"Charm of Making", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"cure",efct1:"immunity",efct2:"",efct3:"",perk:"critical", card:"Storm's End", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"cure",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Storm's End", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"poison",efct2:"shock",efct3:"recoil",perk:"drown", card:"Poisonous Currents", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"poison",efct2:"",efct3:"",perk:"", card:"Poisonous Currents", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"pierce",efct1:"sap",efct2:"",efct3:"",perk:"weakearth", card:"Vine Wrap", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"sap",efct1:"",efct2:"",efct3:"",perk:"weakearth", card:"Vine Wrap", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"defenceup",efct2:"",efct3:"",perk:"attackup", card:"Witch's Brew", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"defenceup",efct2:"",efct3:"",perk:"attackup", card:"Witch's Brew", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"sleep",efct2:"perfectshot",efct3:"",perk:"defencedown", card:"Fellcrest Lullaby", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"sleep",efct2:"",efct3:"",perk:"defencedown", card:"Fellcrest Lullaby", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"stun",efct1:"crush",efct2:"",efct3:"",perk:"interrupt", card:"Rocking Roll", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Rocking Roll", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"regen",efct2:"cure",efct3:"weakearth",perk:"speedup", card:"Peace Pipe", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"cure",efct2:"weakearth",efct3:"",perk:"critical", card:"Peace Pipe", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"flurry",efct1:"defenceup",efct2:"chargetrait",efct3:"",perk:"", card:"Sweet Corn", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"flurry",efct1:"defenceup",efct2:"",efct3:"",perk:"", card:"Sweet Corn", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"regen",efct1:"attackup",efct2:"warp",efct3:"",perk:"immunity", card:"The Spice", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"attackup",efct2:"warp",efct3:"",perk:"immunity", card:"The Spice", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"pierce",efct1:"slow",efct2:"",efct3:"",perk:"shieldbind", card:"Veggie Skewer", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"slow",efct2:"",efct3:"",perk:"critical", card:"Veggie Skewer", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"regen",efct1:"awaken",efct2:"immunity",efct3:"",perk:"critical", card:"Fairy Shield", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Fairy Shield", elmnt:"earth"},
    {rar:"5:star:", pak:"N", efct:"defenceup",efct1:"multitarget",efct2:"attackup",efct3:"",perk:"critical", card:"Healing Splash", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"defenceup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Healing Splash", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"pierce",efct1:"poison",efct2:"",efct3:"",perk:"shieldbind", card:"Ivywood Piercer", elmnt:"earth"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"poison",efct2:"",efct3:"",perk:"critical", card:"Ivywood Piercer", elmnt:"earth"},
    {rar:"5:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"weakfire", card:"Fuming Bunny", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"weakfire", card:"Fuming Bunny", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"cure",efct1:"weakfire",efct2:"multitarget",efct3:"immunity",perk:"critical", card:"Healing Oils", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"cure",efct1:"weakfire",efct2:"",efct3:"",perk:"critical", card:"Healing Oils", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"counter",efct2:"chargetrait",efct3:"",perk:"critical", card:"Hot Chestnuts", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"counter",efct2:"chargetrait",efct3:"",perk:"", card:"Hot Chestnuts", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"break",efct1:"pierce",efct2:"",efct3:"",perk:"burn", card:"Iron Break", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"break",efct1:"",efct2:"",efct3:"",perk:"burn", card:"Iron Break", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"crush",efct2:"burn",efct3:"",perk:"shieldbind", card:"Firestorm", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"crush",efct2:"burn",efct3:"",perk:"critical", card:"Firestorm", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"burn",efct2:"slow",efct3:"",perk:"interrupt", card:"Lava Wave", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"burn",efct2:"slow",efct3:"",perk:"interrupt", card:"Lava Wave", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"chargetrait",efct1:"multitarget",efct2:"burn",efct3:"",perk:"attackup", card:"Volcano", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"chargetrait",efct1:"splash",efct2:"",efct3:"",perk:"attackup", card:"Volcano", elmnt:"fire"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"crush",efct2:"burn",efct3:"",perk:"shieldbind", card:"Blazefury", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"crush",efct2:"burn",efct3:"",perk:"critical", card:"Blazefury", elmnt:"fire"},
    {rar:"5:star:", pak:"N", efct:"pierce",efct1:"bleed",efct2:"",efct3:"",perk:"chargetrait", card:"Bearded Hatchet", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"bleed",efct2:"",efct3:"",perk:"critical", card:"Bearded Hatchet", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"crush",efct1:"",efct2:"",efct3:"",perk:"reset", card:"Caber Toss", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"crush",efct1:"",efct2:"",efct3:"",perk:"reset", card:"Caber Toss", elmnt:"fire"},
    {rar:"5:star:", pak:"N", efct:"break",efct1:"splash",efct2:"",efct3:"",perk:"reset", card:"Dragonslayer", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"break",efct1:"",efct2:"",efct3:"",perk:"reset", card:"Dragonslayer", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"attackup",efct1:"immunity",efct2:"",efct3:"",perk:"critical", card:"Firewall", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"attackup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Firewall", elmnt:"fire"},
    {rar:"5:star:", pak:"N", efct:"taunt",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Flame On", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Flame On", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"leech",efct1:"bleed",efct2:"preventhaste",efct3:"",perk:"critical", card:"Bloodthirster", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"leech",efct1:"bleed",efct2:"",efct3:"",perk:"preventhaste", card:"Bloodthirster", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"haste",efct1:"",efct2:"",efct3:"",perk:"evade", card:"Espresso Shot", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"haste",efct1:"",efct2:"",efct3:"",perk:"evade", card:"Espresso Shot", elmnt:"fire"},
    {rar:"5:star:", pak:"N", efct:"pierce",efct1:"burn",efct2:"",efct3:"",perk:"bleed", card:"Piercing Hellfire", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"burn",efct2:"",efct3:"",perk:"bleed", card:"Piercing Hellfire", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"haste",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Speed of Light", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"haste",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Speed of Light", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"flurry",efct1:"bleed",efct2:"burn",efct3:"multitarget",perk:"stun", card:"Rain of Fire", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"flurry",efct1:"bleed",efct2:"burn",efct3:"multitarget",perk:"critical", card:"Rain of Fire", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"bleed",efct1:"perfectshot",efct2:"",efct3:"",perk:"critical", card:"Quad Slash", elmnt:"fire"},
    {rar:"4:star:", pak:"Y", efct:"bleed",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Quad Slash", elmnt:"fire"},
    {rar:"5:star:", pak:"Y", efct:"regen",efct1:"sleep",efct2:"defenceup",efct3:"",perk:"critical", card:"Night Cap", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"sleep",efct2:"",efct3:"",perk:"defenceup", card:"Night Cap", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"sleep",efct1:"",efct2:"",efct3:"",perk:"weakspirit", card:"Nightmare", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"sleep",efct1:"",efct2:"",efct3:"",perk:"weakspirit", card:"Nightmare", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"accuracydown",efct1:"multitarget",efct2:"interrupt",efct3:"",perk:"critical", card:"Moonbeam", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"accuracydown",efct1:"splash",efct2:"",efct3:"",perk:"interrupt", card:"Moonbeam", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"charm",efct2:"",efct3:"",perk:"stun", card:"Snake Charmer", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"charm",efct2:"",efct3:"",perk:"stun", card:"Snake Charmer", elmnt:"spirit"},
    {rar:"5:star:", pak:"N", efct:"weakspirit",efct1:"attackdown",efct2:"perfectshot",efct3:"",perk:"draintrait", card:"Spent Force", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"weakspirit",efct1:"attackdown",efct2:"recoil",efct3:"",perk:"draintrait", card:"Spent Force", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"slow",efct3:"interrupt",perk:"critical", card:"Pumpkin Field", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"slow",efct3:"",perk:"interrupt", card:"Pumpkin Field", elmnt:"spirit"},
    {rar:"5:star:", pak:"N", efct:"unaware",efct1:"pierce",efct2:"",efct3:"",perk:"bleed", card:"Backstab", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"unaware",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Backstab", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"accuracydown",efct2:"",efct3:"",perk:"interrupt", card:"Flared Up", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"accuracydown",efct2:"",efct3:"",perk:"interrupt", card:"Flared Up", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"luckdown",efct1:"confuse",efct2:"",efct3:"",perk:"unaware", card:"Hard Luck", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"luckdown",efct1:"",efct2:"",efct3:"",perk:"accuracydown", card:"Hard Luck", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"break",efct1:"pierce",efct2:"",efct3:"",perk:"weakspirit", card:"Heart Breaker", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"break",efct1:"",efct2:"",efct3:"",perk:"weakspirit", card:"Heart Breaker", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"preventhaste",efct1:"attackup",efct2:"",efct3:"",perk:"speedup", card:"Shadow Steps", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"preventhaste",efct1:"attackup",efct2:"",efct3:"",perk:"speedup", card:"Shadow Steps", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"perfectshot",efct2:"poison",efct3:"counter",perk:"stun", card:"Spiked Trap", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"poison",efct2:"counter",efct3:"",perk:"stun", card:"Spiked Trap", elmnt:"spirit"},
    {rar:"5:star:", pak:"Y", efct:"evade",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Out of Sight", elmnt:"spirit"},
    {rar:"4:star:", pak:"Y", efct:"evade",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Out of Sight", elmnt:"spirit"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"immunity",efct2:"interrupt",efct3:"",perk:"accuracydown", card:"Avalanche", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"immunity",efct2:"",efct3:"",perk:"interrupt", card:"Avalanche", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"weakspirit",efct1:"",efct2:"",efct3:"",perk:"accuracyup", card:"Channeling Chi", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"weakspirit",efct1:"random",efct2:"",efct3:"",perk:"accuracyup", card:"Channeling Chi", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"interrupt",efct3:"accuracydown",perk:"critical", card:"Easter Eggs", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"flurry",efct2:"interrupt",efct3:"",perk:"accuracydown", card:"Easter Eggs", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"regen",efct1:"slow",efct2:"",efct3:"",perk:"critical", card:"Meditation", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"slow",efct2:"",efct3:"",perk:"critical", card:"Meditation", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"pierce",efct1:"haste",efct2:"stun",efct3:"",perk:"critical", card:"Monk Fu", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"pierce",efct1:"haste",efct2:"",efct3:"",perk:"critical", card:"Monk Fu", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"regen",efct1:"awaken",efct2:"",efct3:"",perk:"speedup", card:"Smelling Salts", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"regen",efct1:"awaken",efct2:"",efct3:"",perk:"speedup", card:"Smelling Salts", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"crush",efct1:"preventhaste",efct2:"interrupt",efct3:"",perk:"critical", card:"Quivering Sole", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"crush",efct1:"preventhaste",efct2:"",efct3:"",perk:"interrupt", card:"Quivering Sole", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"chill",efct2:"",efct3:"",perk:"stun", card:"Deep Breath", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"chill",efct2:"",efct3:"",perk:"stun", card:"Deep Breath", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"chill",efct1:"weakwater",efct2:"pierce",efct3:"",perk:"shieldbind", card:"Ice Shard", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"chill",efct1:"weakwater",efct2:"pierce",efct3:"",perk:"critical", card:"Ice Shard", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"crush",efct2:"drown",efct3:"charm",perk:"defenceup", card:"Kelpies Call", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"splash",efct1:"drown",efct2:"charm",efct3:"",perk:"defenceup", card:"Kelpies Call", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"attackup",efct2:"haste",efct3:"",perk:"mark", card:"Ride of the Valkyries", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"attackup",efct2:"haste",efct3:"",perk:"critical", card:"Ride of the Valkyries", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"crush",efct1:"weakwater",efct2:"chill",efct3:"",perk:"shieldbind", card:"Silverlake Sword", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"crush",efct1:"weakwater",efct2:"",efct3:"",perk:"chill", card:"Silverlake Sword", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"charm",efct1:"weakwater",efct2:"attackup",efct3:"",perk:"luckup", card:"Wet Kiss", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"charm",efct1:"weakwater",efct2:"",efct3:"",perk:"attackup", card:"Wet Kiss", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"break",efct1:"perfectshot",efct2:"weakwater",efct3:"",perk:"shieldbind", card:"Wyrmslayer", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"break",efct1:"accuracyup",efct2:"",efct3:"",perk:"shieldbind", card:"Wyrmslayer", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"pierce",efct1:"interrupt",efct2:"",efct3:"",perk:"bleed", card:"Megalodon Tooth", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"pierce",efct1:"interrupt",efct2:"",efct3:"",perk:"speedup", card:"Megalodon Tooth", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"haste",efct2:"chargetrait",efct3:"",perk:"critical", card:"Hoist the Colours", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"haste",efct2:"",efct3:"",perk:"chargetrait", card:"Hoist the Colours", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"splash",efct1:"bleed",efct2:"weakwater",efct3:"",perk:"critical", card:"Shark Cannon", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"splash",efct1:"bleed",efct2:"weakwater",efct3:"",perk:"critical", card:"Shark Cannon", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"chill",efct1:"taunt",efct2:"stun",efct3:"",perk:"attackdown", card:"Sharp Tongue", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"", card:"Sharp Tongue", elmnt:"water"},
    {rar:"5:star:", pak:"N", efct:"multitarget",efct1:"drown",efct2:"reset",efct3:"",perk:"slow", card:"The Kraken", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"drown",efct2:"interrupt",efct3:"",perk:"slow", card:"The Kraken", elmnt:"water"},
    {rar:"5:star:", pak:"Y", efct:"mark",efct1:"luckdown",efct2:"",efct3:"",perk:"draintrait", card:"Voodoo Ritual", elmnt:"water"},
    {rar:"4:star:", pak:"Y", efct:"mark",efct1:"",efct2:"",efct3:"",perk:"luckdown", card:"Voodoo Ritual", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"crush",efct2:"shock",efct3:"",perk:"stun", card:"Divine Storm", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"shock",efct1:"accuracydown",efct2:"",efct3:"",perk:"speedup", card:"Flash of Lightning", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Justicar", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"weakair", card:"The Equalizer", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"weakair",efct2:"counter",efct3:"",perk:"critical", card:"Hurricane Barrier", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"extendshock",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Quicksilver", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"weakair",efct2:"",efct3:"",perk:"stun", card:"Wind Dart", elmnt:"air"},
    {rar:"4:star:", pak:"N", efct:"bleed",efct1:"interrupt",efct2:"",efct3:"",perk:"interrupt", card:"Crippling Spell", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"weakearth",efct1:"",efct2:"",efct3:"",perk:"extendpoison", card:"Deadly Venom", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"poison",efct1:"",efct2:"",efct3:"",perk:"mark", card:"Toxic Vengeance", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"pierce",efct1:"weakearth",efct2:"",efct3:"",perk:"interrupt", card:"Green Ray", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"crush",efct2:"weakearth",efct3:"",perk:"extendpoison", card:"Clay Shower", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"regen",efct1:"stun",efct2:"",efct3:"",perk:"interrupt", card:"Merry Christmas", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"flurry",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Uber Cornholio", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"accuracyup",efct2:"",efct3:"",perk:"shieldbind", card:"Elven Precision", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"hpup",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Puck's Grace", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"weakearth",efct2:"counter",efct3:"",perk:"critical", card:"Shield of The Nature", elmnt:"earth"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"weakfire",efct2:"",efct3:"",perk:"interrupt", card:"Blazing Ray", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"interrupt",efct1:"",efct2:"",efct3:"",perk:"extendburn", card:"Pyroclastic Sphere", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"weakfire",efct1:"",efct2:"",efct3:"",perk:"extendburn", card:"Scorching Flames", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"taunt",efct1:"immunity",efct2:"",efct3:"",perk:"speedup", card:"Dragon Skin", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"attackup",efct1:"",efct2:"",efct3:"",perk:"cure", card:"Salamander Ale", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"weakfire",efct2:"",efct3:"",perk:"extendburn", card:"Igni Ferroque", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"burn",efct2:"",efct3:"",perk:"interrupt", card:"Pyroclastic Strike", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"pierce",efct1:"",efct2:"",efct3:"",perk:"extendbleed", card:"Pierced Heart", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"bleed",efct2:"",efct3:"",perk:"break", card:"Pyro Dagger", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"regen",efct2:"",efct3:"",perk:"burn", card:"Turkey Sagitta", elmnt:"fire"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"charm",efct2:"",efct3:"",perk:"interrupt", card:"Adorable Pugs", elmnt:"neutral"},
    {rar:"4:star:", pak:"Y", efct:"perfectshot",efct1:"burn",efct2:"",efct3:"",perk:"accuracydown", card:"Apollo's Arrow", elmnt:"neutral"},
    {rar:"5:star:", pak:"Y", efct:"multitarget",efct1:"hpup",efct2:"",efct3:"",perk:"defenceup", card:"Rejuvenate All", elmnt:"neutral"},
    {rar:"4:star:", pak:"Y", efct:"multitarget",efct1:"hpup",efct2:"",efct3:"",perk:"defenceup", card:"Rejuvenate All", elmnt:"neutral"},
    {rar:"5:star:", pak:"Y", efct:"taunt",efct1:"defenceup",efct2:"",efct3:"",perk:"critical", card:"Magnet Shield", elmnt:"neutral"},
    {rar:"4:star:", pak:"Y", efct:"taunt",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Magnet Shield", elmnt:"neutral"},
    {rar:"5:star:", pak:"Y", efct:"attackup",efct1:"",efct2:"",efct3:"",perk:"awaken", card:"Safeguard", elmnt:"neutral"},
    {rar:"4:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Safeguard", elmnt:"neutral"},
    {rar:"4:star:", pak:"N", efct:"counter",efct1:"attackup",efct2:"",efct3:"",perk:"chargetrait", card:"Necropower", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"pierce",efct2:"weakspirit",efct3:"",perk:"mark", card:"Malefix", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"luckdown",efct2:"luckup",efct3:"",perk:"weakspirit", card:"Retribution Curse", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"flurry",efct2:"leech",efct3:"weakspirit",perk:"critical", card:"Vampiric Lord", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"splash",efct1:"evade",efct2:"",efct3:"",perk:"critical", card:"Obscuring Explode", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"splash",efct1:"weakspirit",efct2:"",efct3:"",perk:"sleep", card:"Ninja Grenade", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"unaware",efct2:"",efct3:"",perk:"speedup", card:"Whispering Blade", elmnt:"spirit"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"stun",efct2:"",efct3:"",perk:"luckup", card:"Ascetic Lesson", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"crush",efct1:"weakwater",efct2:"",efct3:"",perk:"interrupt", card:"Frost Ray", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"regen",efct2:"counter",efct3:"",perk:"weakwater", card:"Poseidon\'s Will", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"drown",efct1:"luckup",efct2:"",efct3:"",perk:"weakwater", card:"Triton's Will", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"counter",efct1:"immunity",efct2:"",efct3:"",perk:"attackup", card:"Fafnir Blood", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"immunity",efct1:"awaken",efct2:"",efct3:"",perk:"luckup", card:"Ice Queen Protector", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"defenceup",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Mead Gulp", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"multitarget",efct1:"pierce",efct2:"chill",efct3:"",perk:"shieldbind", card:"Silverlake Shards", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"perfectshot",efct1:"interrupt",efct2:"",efct3:"",perk:"drown", card:"Ancient Mariner", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"regen",efct1:"bamboozle",efct2:"hpup",efct3:"",perk:"speedup", card:"Caribbean Cocktail", elmnt:"water"},
    {rar:"4:star:", pak:"N", efct:"pierce",efct1:"",efct2:"",efct3:"",perk:"mark", card:"Mark of Vengeance", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Dagger of Truth", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"crush",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Barrier Crusher", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"defenceup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Defensive Strike", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"shock",efct2:"",efct3:"",perk:"stun", card:"Divine Thunder", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"awaken",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Vigilant Shield", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"shock",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Lightning Spear", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Quartzstone", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"shock",efct2:"",efct3:"",perk:"weakair", card:"Shocking Axe", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"shock",efct2:"",efct3:"",perk:"weakair", card:"Shocking Bag", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"shock",efct1:"",efct2:"",efct3:"",perk:"weakair", card:"Shocking Sword", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"weakair",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Storm Dagger", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"weakair", card:"Sword of Justice", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Diverting Pin", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"",efct1:"",efct2:"",efct3:"",perk:"extendshock", card:"Eletric Shot", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"weakair", card:"Perfect Dart", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Pin Barrage", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"shock",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Shocking Dart", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"shock",efct1:"",efct2:"",efct3:"",perk:"weakair", card:"Shocking Pin", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"weakair",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Storm Dart", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"weakair",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Storm Edge", elmnt:"air"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Tempest Amulet", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"weakair",efct2:"",efct3:"",perk:"critical", card:"Wind Barrier", elmnt:"air"},
    {rar:"3:star:", pak:"N", efct:"interrupt",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Crippling Bolt", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"interrupt",efct2:"",efct3:"",perk:"interrupt", card:"Earth Quake", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"",efct1:"",efct2:"",efct3:"",perk:"extendpoison", card:"Feed the Toxins", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"break",efct1:"defencedown",efct2:"",efct3:"",perk:"poison", card:"Mischievous Break", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"poison",efct2:"",efct3:"",perk:"weakearth", card:"Poison Cloud", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"poison",efct2:"",efct3:"",perk:"critical", card:"Poison Grenade", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Stunning Earth", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"weakearth",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Terra Missile", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"weakearth",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Toxic Bolt", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"poison",efct1:"",efct2:"",efct3:"",perk:"mark", card:"Witchcraft", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Byson Shield", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Christmas Tree", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"flurry",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Cornholio", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"splash",efct1:"weakearth",efct2:"",efct3:"",perk:"extendpoison", card:"Dirty Bomb", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"pierce",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Piercing Spear", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"poison",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Poisonous Dung", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Sundered Rocks", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"weakearth",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Terra Sword", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"immunity", card:"The Scabber", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"regen",efct2:"warp",efct3:"",perk:"critical", card:"Warped Seeds", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"bleed",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Bleeding Thorn", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Diverting Tip", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Ivywood Amulet", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"hpup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Fairy Blessing", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"weakearth",efct2:"",efct3:"",perk:"critical", card:"Forest Barrier", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"accuracyup", card:"Perfect Sight", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"poison",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Poisonous Dart", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"poison",efct1:"",efct2:"",efct3:"",perk:"weakearth", card:"Poisonous Tip", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"sleep",efct2:"",efct3:"",perk:"poison", card:"Sleeping Dust", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"weakearth",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Terra Tip", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Tip Barrage", elmnt:"earth"},
    {rar:"3:star:", pak:"N", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"poison", card:"Rooster Arrow", elmnt:"earth"},
    {rar:"3:star:", pak:"Y", efct:"accuracydown",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Blinding Flame", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"burn",efct2:"",efct3:"",perk:"interrupt", card:"Burning Blast", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"burn",efct2:"",efct3:"",perk:"critical", card:"Burning Grenade", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"weakfire", card:"Burning Missile", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"luckup", card:"Cloak of Flames", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"weakfire",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Fire Bolt", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"weakfire",efct2:"",efct3:"",perk:"interrupt", card:"Oil Spill", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Stunning Heat", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"weakfire", card:"Burning Blade", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Burning Club", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"weakfire", card:"Burning Dagger", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Fiery Axe", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"splash",efct1:"weakfire",efct2:"",efct3:"",perk:"extendburn", card:"Fuel the Fire", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"immunity",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Furious Fist", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Hot Boulder", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"burn",efct2:"",efct3:"",perk:"interrupt", card:"Magmatic Rocks", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"attackup",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Monster Juice", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Mutton Chops", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"weakfire",efct2:"",efct3:"",perk:"critical", card:"Oil Bag", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"immunity",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Salamander Skin", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"",efct1:"",efct2:"",efct3:"",perk:"extendbleed", card:"Bleeding Heart", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Boiling Coffee", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"burn",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Burning Disc", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"burn",efct2:"",efct3:"",perk:"critical", card:"Diverting Disc", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"flurry",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Fiery Stars", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Perfect Cut", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"weakfire",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Oil Dart", elmnt:"fire"},
    {rar:"3:star:", pak:"N", efct:"regen",efct1:"",efct2:"",efct3:"",perk:"burn", card:"Turkey Arrow", elmnt:"fire"},
    {rar:"3:star:", pak:"Y", efct:"accuracydown",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Blinding Spirit", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"evade",efct2:"",efct3:"",perk:"critical", card:"Cloak Party", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"confuse",efct2:"",efct3:"",perk:"weakspirit", card:"Confuse Cloud", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"confuse",efct2:"",efct3:"",perk:"critical", card:"Confuse Grenade", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"weakspirit",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Darken Missile", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"leech",efct1:"",efct2:"",efct3:"",perk:"draintrait", card:"Discharging Ray", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"weakspirit",efct2:"",efct3:"",perk:"mark", card:"Hex", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"leech",efct1:"",efct2:"",efct3:"",perk:"bleed", card:"Life Leecher", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"counter",efct2:"",efct3:"",perk:"critical", card:"Menacing Gloom", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"luckdown",efct2:"",efct3:"",perk:"luckup", card:"Setback", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"flurry",efct2:"leech",efct3:"",perk:"critical", card:"Vampiric Bats", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"evade",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Cloaked", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"confuse",efct1:"",efct2:"",efct3:"",perk:"weakspirit", card:"Confuse Dart", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"weakspirit",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Darkness Spike", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"immunity", card:"Defrost Amulet", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"splash",efct1:"weakspirit",efct2:"",efct3:"",perk:"stun", card:"Explosive Gadget", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"leech",efct2:"",efct3:"",perk:"weakspirit", card:"Leech Boomerang", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"unaware", card:"Perfect Stab", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"splash",efct1:"evade",efct2:"",efct3:"",perk:"critical", card:"Smoke Bomb", elmnt:"spirit"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Spike Barrage", elmnt:"spirit"},
    {rar:"3:star:", pak:"N", efct:"drown",efct1:"",efct2:"",efct3:"",perk:"weakwater", card:"Apnoea", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"break",efct1:"",efct2:"",efct3:"",perk:"stun", card:"Breaking Chakra", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"weakwater",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Ice Bolt", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"chill",efct2:"",efct3:"",perk:"critical", card:"Chill Grenade", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"chill",efct1:"",efct2:"",efct3:"",perk:"weakwater", card:"Chill Missile", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"chill",efct2:"",efct3:"",perk:"weakwater", card:"Chill Stones", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"chill", card:"Chilling Jab", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"luckup", card:"Karmick Kick", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"luckup",efct1:"",efct2:"",efct3:"",perk:"cure", card:"Karmic Protection", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"flurry",efct1:"chill",efct2:"",efct3:"",perk:"critical", card:"Snowballs Squall", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"weakwater", card:"Tidal Kick", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"regen",efct2:"",efct3:"",perk:"weakwater", card:"Tides Control", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"weakwater",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Wet Missile", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"chill",efct2:"",efct3:"",perk:"critical", card:"Chill Axe", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"chill",efct1:"",efct2:"",efct3:"",perk:"weakwater", card:"Chill Blade", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"chill",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Chill Club", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"multitarget",efct1:"pierce",efct2:"chill",efct3:"",perk:"critical", card:"Chilling Shards", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"counter",efct1:"",efct2:"",efct3:"",perk:"immunity", card:"Frostbite Shield", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"chill", card:"Glacier", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Mammoth Shield", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"",efct1:"",efct2:"",efct3:"",perk:"defenceup", card:"Mead Sip", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"pierce",efct1:"chill",efct2:"",efct3:"",perk:"critical", card:"Piercing Shard", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"immunity",efct1:"",efct2:"",efct3:"",perk:"luckup", card:"Valkyries\'s Shield' , element:'water"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"weakwater",efct2:"",efct3:"",perk:"critical", card:"Wet Bag", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"weakwater",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Wet Dagger", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"counter",efct1:"",efct2:"",efct3:"",perk:"immunity", card:"Wyrm\'s Blood", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"",efct1:"",efct2:"",efct3:"",perk:"mark", card:"Black Spot", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"bamboozle",efct1:"luckup",efct2:"",efct3:"",perk:"critical", card:"Grog Bottle", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"pierce",efct1:"weakair",efct2:"",efct3:"",perk:"critical", card:"Mistral Strike", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"interrupt",efct2:"",efct3:"",perk:"critical", card:"Oyster Blunderbuss", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"perfectshot",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Perfect Slash", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"weakwater",efct1:"",efct2:"",efct3:"",perk:"drown", card:"Piranha Pistol", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"weakfire",efct1:"",efct2:"",efct3:"",perk:"bamboozle", card:"Rum Shower", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"pierce",efct1:"",efct2:"",efct3:"",perk:"bamboozle", card:"Stingray Dart", elmnt:"water"},
    {rar:"3:star:", pak:"N", efct:"regen",efct1:"bamboozle",efct2:"",efct3:"",perk:"hpup", card:"Tropical Juice", elmnt:"water"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Arcane Grenade", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Arcane Missile", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Drop Shield", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Epicentre", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Healing Soul", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"cure",efct2:"",efct3:"",perk:"accuracyup", card:"Guide Dog", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Party Bubble", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"sleep",efct1:"",efct2:"",efct3:"",perk:"slow", card:"Sleeping Sceptre", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Stunning Staff", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"bleed",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Bleeding Dagger", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Explosive Bag", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Gravy Barrel", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"counter",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Impale Shield", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Interrupt Sword", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Power Shield", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"stun",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Stunning Boulder", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"critical", card:"War Axe", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"bleed",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Bleeding Edge", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"weakfire",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Combustibolt", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"multitarget",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Destructive Arrow", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Diverting Arrow", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"splash",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Diverting Dart", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"speedup", card:"Hasty Arrow", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"interrupt", card:"Interrupt Arrow", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"attackup", card:"Lentil Soup", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Shielding Light", elmnt:"neutral"},
    {rar:"3:star:", pak:"Y", efct:"",efct1:"",efct2:"",efct3:"",perk:"critical", card:"Silver Dart", elmnt:"neutral"}
   // {rar:"|", pak:"|", efct:"|",efct1:"|",efct2:"|",efct3:"|",perk:"|", card:"|", elmnt:"|"}
  ]
  
};